name       : libxcursor
version    : 1.1.15
release    : 11
source     :
    - https://www.x.org/releases/individual/lib/libXcursor-1.1.15.tar.gz : 449befea2b11dde58ba3323b2c1ec30550013bd84d80501eb56d0048e62251a1
license    :
    - MIT
summary    : X Cursor management library
component  : xorg.library
description: |
    Xcursor is a simple library designed to help locate and load cursors for the
    X Window System. Cursors can be loaded from files or memory and can exist in
    several sizes; the library automatically picks the best size.
    When using images loaded from files, Xcursor prefers to use the Render
    extension's CreateCursor request for rendering cursors.  Where the Render
    extension is not supported, Xcursor maps the cursor image to a standard X
    cursor and uses the core X protocol CreateCursor request.
builddeps  :
    - pkgconfig(xextproto)
    - pkgconfig32(xrender)
    - pkgconfig32(xfixes)
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
