name       : libxcursor
version    : 1.2.0
release    : 14
source     :
    - https://www.x.org/releases/individual/lib/libXcursor-1.2.0.tar.gz : ad5b2574fccaa4c3fa67b9874fbed863d29ad230c784e9a08b20692418f6a1f8
license    :
    - MIT
summary    : X Cursor management library
component  : xorg.library
description: |
    Xcursor is a simple library designed to help locate and load cursors for the
    X Window System. Cursors can be loaded from files or memory and can exist in
    several sizes; the library automatically picks the best size.
    When using images loaded from files, Xcursor prefers to use the Render
    extension's CreateCursor request for rendering cursors.  Where the Render
    extension is not supported, Xcursor maps the cursor image to a standard X
    cursor and uses the core X protocol CreateCursor request.
builddeps  :
    - pkgconfig(xextproto)
    - pkgconfig32(xrender)
    - pkgconfig32(xfixes)
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
